apiVersion: v1
kind: Service
metadata:
  name: {{ include "JavaApp.fullname" . }}
  labels:
    {{- include "JavaApp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "JavaApp.selectorLabels" . | nindent 4 }}
